### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by onns** [LouisYLWang/Sync-Sofa#44]
- [x] close()方法修复
- [x] video call 的连接状态与socket同步
- [x] popup处的video feature 和 chat feature 与本地存储不同步
- [x] ~~在popup里可以修改的属性，option页面可以去掉，只留下server、debug和notification~~，这个不用改了
- [ ] 若一方未开启相应功能，另一方应该有所提示
- [ ] video call 音量控件
- [ ] 语音通话
- [x] popup ui修改
- [ ] 本地播放mp4下的ui修复
- [x] feature的修改会导致start按钮不可点击
- [ ] 多人用户
- [ ] 视频窗口的缩放
- [x] 多版本控制（当用户装了多个版本的插件，互相之间不冲突）
- [x] 新消息震动提醒，如果已经处于震动状态，震动会消失
